### ISSUE TITLE
[proposal] describe expectations

### ISSUE THREAD

**Issue by elstamey** [helpmeabstract/helpmeabstract#18]
What can the Submitter expect as far as feedback?  For example, I found comments on my gist after a day, but I'm not sure if follow-up feedback must be requested.  Should I expect continuous feedback on the initial gist and revisions? Or do I re-submit it?  I thought I would hear from more than one person.

**Comment by greydnls** [comment]
👍  I like this idea. It would be a good thing to add to the thank you page, I think.

**Comment by elstamey** [comment]
If you can briefly describe how this should work, @kayladnls, I'll submit a PR.

AFAIK, when you revise, you should resubmit the gist.  It is possible that the timing of your submission will miss most of the reviewers if they happen to all be at a conference.  It seems like because of this, submitters should feel free to re-post.

**Comment by greydnls** [comment]
@elstamey I've wanted to add a confirmation email to the submitter for a while. I was thinking about it and I think the best way to do this would be to kill 2 birds with one stone. 

Send confirmation email to submitter and include what to expect in that email body. 

I wouldn't re-submit for a revision, personally. If someone gives you feedback and you revise I would update the gist and make a comment mentioning the person who gave the feedback. AFAIK people do get notifications when they're explicitly mentioned on gists. Could be wrong there, though. 

If you don't recieve any feedback then resubmitting after a few days would be fine because yes, often times people will be at conferences or busy. 

People can also feel free to reach out to me directly on twitter if they have any problems.
