### ISSUE TITLE
Cannot run project as is

### ISSUE THREAD

**Issue by elstamey** [helpmeabstract/helpmeabstract#25]
I do not have a .env template to work from to configure the project, and the phinx.yml assumes the mysql development password is `secret`.  I'd like to submit revisions to the readme and a dist version of the .env file to help future contributors.  Would that be OK?

**Comment by greydnls** [comment]
Yes please.

**Comment by elstamey** [comment]
can you give me a stubbed .env?  Email is fine.

**Comment by elstamey** [comment]
@kayladnls i don't know what variables need to be in the .env file.

**Comment by rogeriopradoj** [comment]
Hi, @elstamey ! I took a look at https://github.com/greydnls/helpmeabstract/blob/master/public/index.php and just found two variables: `DATABASE_USER` and `DATABASE_PASSWORD`.

So I guess the `.env` file should be:

``` .env
DATABASE_USER=root
DATABASE_PASSWORD=secret
```

Have you started already the work for future contributors already? Otherwise I'm going to send some Pull Requests soon including some things, ok?

See ya!

**Comment by elstamey** [comment]
I am pretty sure @greydnls is rewriting this in another language.

**Comment by rogeriopradoj** [comment]
Really? Tell us more about it!
